### ISSUE TITLE
Project abandonned ?

### ISSUE THREAD

**Issue by DjebbZ** [davidMis/ElmPlugin#2]
I'd like to know the status of the project, to whether or not to use IntelliJ to code in Elm or switch to something else.

**Comment by davidMis** [comment]
I haven't been keeping up with the latest changes in Elm, so I can't guarantee this plugin still works as well as it should. I'd like to come back to this project, but honestly I imagine there are probably better tools out there at this point.

**Comment by DjebbZ** [comment]
I installed it and used it briefly. At least it didn't crash, but indeed was far from complete. Ok.

Thanks for your quick answer and honesty about it.
